language: php

git:
    depth: 1

cache:
    directories:
        - $HOME/.composer/cache

services:
    - mongodb

env:
    - DEPENDENCIES=''
    - DEPENDENCIES='low'
    - DEPENDENCIES='beta'

php:
    - 7.0
    - 7.1
    - 7.2
    - 7.3

before_install: echo 'extension = "mongodb.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
    - if [[ $DEPENDENCIES = 'beta' ]]; then composer config minimum-stability beta; fi
    - if [[ ! $DEPENDENCIES || $DEPENDENCIES = 'beta' ]]; then composer update --prefer-dist --no-progress --no-suggest --ansi; fi
    - if [[ $DEPENDENCIES = 'low' ]]; then composer update --prefer-dist --no-progress --no-suggest --prefer-stable --prefer-lowest --ansi; fi

script:
    - vendor/bin/php-cs-fixer fix --dry-run --diff src
    - vendor/bin/behat
    - vendor/bin/phpstan analyse src

notifications:
    email: false
